services:
  # Web Service cho OneShop Application
  - type: web
    name: oneshop-app
    env: docker
    dockerfilePath: ./Dockerfile
    # Render sẽ tự động phát hiện PORT từ environment
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: APP_URL
        value: https://oneshop-app.onrender.com  # Thay đổi theo tên service của bạn
      
      # MySQL Database Configuration (External Service)
      - key: DB_HOST
        sync: false  # Sẽ được set manual trong Render Dashboard
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        sync: false  # Database name
      - key: DB_USERNAME
        sync: false  # MySQL username
      - key: DB_PASSWORD
        sync: false  # MySQL password
      
      # Mail Configuration
      - key: MAIL_USERNAME
        value: oneshop123vn@gmail.com
      - key: MAIL_PASSWORD
        sync: false  # Sẽ được set manual trong Render Dashboard
      
      # Payment & OAuth Configuration  
      - key: MOMO_PARTNER_CODE
        value: MOMOKYA420251014
      - key: MOMO_ACCESS_KEY
        value: hBRIivWIlNu2WRhE
      - key: MOMO_SECRET_KEY
        sync: false  # Sẽ được set manual trong Render Dashboard
      - key: FACEBOOK_CLIENT_ID
        sync: false  # Sẽ được set manual trong Render Dashboard
      - key: FACEBOOK_CLIENT_SECRET
        sync: false  # Sẽ được set manual trong Render Dashboard
        
    healthCheckPath: /actuator/health
    # Auto-scaling configuration
    scalingPolicy:
      minInstances: 1
      maxInstances: 3
      targetCPUPercent: 70
      targetMemoryPercent: 80

# Không cần PostgreSQL database vì sử dụng external MySQL
